

<?php
echo '<?xml version="1.0" encoding="UTF-8"?>'; // Tambahkan header xml
?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>XML Sitemap</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style type="text/css">
		body {
			font-family: Helvetica, Arial, sans-serif;
			font-size: 13px;
			color: #545353;
		}
		table {
			border: none;
			border-collapse: collapse;
		}
		#sitemap tr:nth-child(odd) td {
			background-color: #eee !important;
		}
		#sitemap tbody tr:hover td {
			background-color: #ccc;
		}
		#sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
			color: #000;
		}
		#content {
			margin: 0 auto;
			width: 1000px;
		}
		.expl {
			margin: 18px 3px;
			line-height: 1.2em;
		}
		.expl a {
			color: #da3114;
			font-weight: 600;
		}
		.expl a:visited {
			color: #da3114;
		}
		a {
			color: #000;
			text-decoration: none;
		}
		a:visited {
			color: #777;
		}
		a:hover {
			text-decoration: underline;
		}
		td {
			font-size:11px;
		}
		th {
			text-align:left;
			padding-right:30px;
			font-size:11px;
		}
		thead th {
			border-bottom: 1px solid #000;
		}
	</style>
</head>
<body>
	<div id="content">
		<h1>XML Sitemap</h1>
		<p class="expl">
			Generated by <a href="https://yoa.st/1y5" target="_blank" rel="noopener noreferrer">Yoast</a> <a href="https://yoa.st/1y6" target="_blank" rel="noopener noreferrer">SEO</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>
			You can find more information about XML sitemaps on <a href="http://sitemaps.org" target="_blank" rel="noopener noreferrer">sitemaps.org</a>.
		</p>
		<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
			<p class="expl">
				This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
			</p>
			<table id="sitemap" cellpadding="3">
				<thead>
				<tr>
					<th width="75%">Sitemap</th>
					<th width="25%">Last Modified</th>
				</tr>
				</thead>
				<tbody>
					<tr>
						<td><a href="https://www.mitrarenov.com/member/register"><loc>https://www.mitrarenov.com/member/register</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/ https://bit.ly/whatsapp-mitrarenov"><loc>https://www.mitrarenov.com/ https://bit.ly/whatsapp-mitrarenov</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/member/register"><loc>https://www.mitrarenov.com/member/register</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com"><loc>https://www.mitrarenov.com</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/member/login"><loc>https://www.mitrarenov.com/member/login</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com"><loc>https://www.mitrarenov.com</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/simulasi-kpr"><loc>https://www.mitrarenov.com/simulasi-kpr</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/halaman/tentang-kami"><loc>https://www.mitrarenov.com/halaman/tentang-kami</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/halaman/cara-kerja"><loc>https://www.mitrarenov.com/halaman/cara-kerja</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/halaman/hubungi-kami"><loc>https://www.mitrarenov.com/halaman/hubungi-kami</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>					
					<tr>
						<td><a href="https://www.mitrarenov.com/berita"><loc>https://www.mitrarenov.com/berita</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/#jasa"><loc>https://www.mitrarenov.com/#jasa</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/jasa-desain-arsitek"><loc>https://www.mitrarenov.com/jasa/jasa-desain-arsitek</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/jasa-interior-rumah"><loc>https://www.mitrarenov.com/jasa/jasa-interior-rumah</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/pembuatan-imb"><loc>https://www.mitrarenov.com/jasa/pembuatan-imb</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/gallery"><loc>https://www.mitrarenov.com/gallery</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>					
					<tr>
						<td><a href="https://www.mitrarenov.com/portofolio"><loc>https://www.mitrarenov.com/portofolio</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<?php foreach($merawat as $m): ?>
					<tr>
						<td><a href="<?= base_url('portofolio/' . $m->slug); ?>"><loc><?= base_url('portofolio/' . $m->slug); ?></loc></a></td>
						<td><lastmod><?= $m->created ?></lastmod></td>
					</tr>
					<?php endforeach; ?>
					<tr>
						<td><a href="https://www.mitrarenov.com/desain-rumah"><loc>https://www.mitrarenov.com/desain-rumah</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Bangun-Rumah"><loc>https://www.mitrarenov.com/jasa/Bangun-Rumah</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Membangun-Ruko"><loc>https://www.mitrarenov.com/jasa/Membangun-Ruko</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					
					<?php foreach($artikel as $a): ?>
					<tr>
						<td><a href="<?= $a->slug ?>"><loc><?= $a->slug ?></loc></a></td>
						<td><lastmod><?= $a->date ?></lastmod></td>
					</tr>
					<?php endforeach; ?>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Membangun-rumah-kost"><loc>https://www.mitrarenov.com/jasa/Membangun-rumah-kost</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Bangun-Toko"><loc>https://www.mitrarenov.com/jasa/Bangun-Toko</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/membuat-dak"><loc>https://www.mitrarenov.com/jasa/membuat-dak</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Menambah-Ruangan"><loc>https://www.mitrarenov.com/jasa/Menambah-Ruangan</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/meningkat-rumah"><loc>https://www.mitrarenov.com/jasa/meningkat-rumah</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Pengecatan"><loc>https://www.mitrarenov.com/jasa/Pengecatan</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Pembuatan-Kolam-Renang"><loc>https://www.mitrarenov.com/jasa/Pembuatan-Kolam-Renang</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Renovasi-Rumah-Lainnya"><loc>https://www.mitrarenov.com/jasa/Renovasi-Rumah-Lainnya</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/membuat-taman-dan-kolam-ikan"><loc>https://www.mitrarenov.com/jasa/membuat-taman-dan-kolam-ikan</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Jasa-Desain-Arsitek"><loc>https://www.mitrarenov.com/jasa/Jasa-Desain-Arsitek</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/service-&amp;-cuci-ac"><loc>https://www.mitrarenov.com/jasa/service-&amp;-cuci-ac</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Cuci-Toren"><loc>https://www.mitrarenov.com/jasa/Cuci-Toren</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Instalasi-CCTV"><loc>https://www.mitrarenov.com/jasa/Instalasi-CCTV</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/jasa/Jasa-Interior-Rumah"><loc>https://www.mitrarenov.com/jasa/Jasa-Interior-Rumah</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/halaman/kebijakan-privasi"><loc>https://www.mitrarenov.com/halaman/kebijakan-privasi</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/halaman/syarat-ketentuan"><loc>https://www.mitrarenov.com/halaman/syarat-ketentuan</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/halaman/tanya-jawab"><loc>https://www.mitrarenov.com/halaman/tanya-jawab</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
					<tr>
						<td><a href="https://www.mitrarenov.com/member/lupa-password"><loc>https://www.mitrarenov.com/member/lupa-password</loc></a></td>
						<td><lastmod><?= date('Y-m-d') ?></lastmod></td>
					</tr>
				</tbody>
			</table>
		</xsl:if>
	</div>
</body>
</html>